---
# RedHat related OSs
- name: Yum install {{ item }}
  action: yum pkg={{ item }} state=installed
  when: "ansible_os_family == 'RedHat'"
  with_items:
  - wget
  - tar
  - gzip

- name: Ubuntu 14 install software-properties-common
  apt: name=software-properties-common
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

- name: Ubuntu 14 install OpenJDK PPA repo
  apt_repository: repo='ppa:openjdk-r/ppa'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

# Debian related OSs
- name: Apt install {{ item }}
  action: apt pkg={{ item }} state=installed update_cache=yes cache_valid_time=604800
  when: "ansible_os_family == 'Debian'"
  with_items:
  - wget
  - tar
  - gzip

# download only in the ansible master node
- local_action: get_url url={{ hadoop_mirrors|random }}/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz dest="{{ tmp }}/hadoop-{{ hadoop_version }}.tar.gz" force=no
  become: false
  register: result
  until: result|success
  retries: 5
  delay: 2
  when: hadoop_type_of_node == 'master'

# other nodes wait for it
- local_action: wait_for path="{{ tmp }}/hadoop-{{ hadoop_version }}.tar.gz"
  become: false
  when: hadoop_type_of_node != 'master'

- copy: src={{ tmp }}/hadoop-{{ hadoop_version }}.tar.gz dest=/opt/hadoop-{{ hadoop_version }}.tar.gz force=no

- unarchive: src=/opt/hadoop-{{ hadoop_version }}.tar.gz dest=/opt creates=/opt/hadoop-{{ hadoop_version }} copy=no

- file: dest={{ hadoop_home }} src=/opt/hadoop-{{ hadoop_version }} state=link

- file: dest=/opt/hadoop src={{ hadoop_home }} state=link

- name: Add hadoop bin dir to system-wide $PATH.
    copy:
      dest: /etc/profile.d/hadoop-path.sh
      content: 'PATH=$PATH:{{ hadoop_home }}/bin'

- lineinfile: dest="{{ hadoop_home }}/etc/hadoop/hadoop-env.sh" regexp=JAVA_HOME= line="export JAVA_HOME=/usr/java/default"

- lineinfile: dest="~/.bash_profile" regexp=HADOOP_HOME= line="export HADOOP_HOME={{ hadoop_home }}"
    state=present
    create=true
    insertafter=EOF
  become: false
