---

#- name: Download Oracle JDK8
#  local_action: get_url url=https://s3.amazonaws.com/datapassport-lib/{{ jdk_file }}
#  register: result

- name: Yum install JDK8
  yum:
    name: '{{ jdk_mirrors|random }}/{{ jdk_file }}'
    state: present
  when: "ansible_os_family == 'RedHat'"