---
- debug: msg="restart all hadoop components"
  changed_when: true
  notify:
   - restart hadoop-dfs
   - restart yarn-resourcemanager
   - restart hadoop-datanode
   - restart yarn-nodemanager
   - refreshDFSNodes
   - refreshYarnNodes
   - createHomeDirs
  tags:
   - restart
