- name: restart hadoop-dfs
  action: shell {{ hadoop_home }}/sbin/hadoop-daemon.sh  --script hdfs stop namenode; {{ hadoop_home }}/sbin/hadoop-daemon.sh  --script hdfs start namenode
  when: ( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'namenode' )
  
- name: restart yarn-resourcemanager
  action: shell {{ hadoop_home }}/sbin/yarn-daemon.sh stop resourcemanager; {{ hadoop_home }}/sbin/yarn-daemon.sh start resourcemanager
  when: ( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'resourcemanager' )
   
- name: restart hadoop-datanode
  action: shell {{ hadoop_home }}/sbin/hadoop-daemon.sh  --script hdfs stop datanode; {{ hadoop_home }}/sbin/hadoop-daemon.sh  --script hdfs start datanode
  when: ( hadoop_type_of_node == 'slave' ) or ( hadoop_type_of_node == 'datanode' )
  
- name: restart yarn-nodemanager
  action: shell {{ hadoop_home }}/sbin/yarn-daemon.sh stop nodemanager; {{ hadoop_home }}/sbin/yarn-daemon.sh start nodemanager
  when: ( hadoop_type_of_node == 'slave' ) or ( hadoop_type_of_node == 'nodemanager' )
  
- name: refreshDFSNodes
  command: "{{ hadoop_home }}/bin/hdfs dfsadmin -refreshNodes"
  when: ( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'namenode' )
  ignore_errors: yes

- name: refreshYarnNodes
  command: "{{ hadoop_home }}/bin/yarn rmadmin -refreshNodes"
  when: ( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'resourcemanager' )
  ignore_errors: yes

- name: createHomeDirs
  shell: |
    {{ hadoop_home }}/bin/hadoop fs -mkdir -p /home/{{ item }}
    {{ hadoop_home }}/bin/hadoop fs -chown -R {{ item }}:{{ item }} /home/{{ item }}
  with_items:
    - hive
    - "{{ ansible_env.SUDO_USER }}"
    - "{{ ansible_user_id }}"
  when: ( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'resourcemanager' )

- name: createTmpDirs
  shell: |
    {{ hadoop_home }}/bin/hadoop fs -mkdir -p /tmp
    {{ hadoop_home }}/bin/hadoop fs -chmod -R 777 /tmp
  when: ( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'resourcemanager' )
